### ISSUE TITLE
Video not shared

### ISSUE THREAD

**Issue by toabctl** [jangouts/jangouts#124]
When using my camera (on jangouts.suse.de) , I can see myself but others can not see me and I can't see others.
In the js console, I get
```
Data channel not open yet. Skipping
app-e8e81040.js:133 Data channel not open yet. Skipping
app-e8e81040.js:133 Data channel not open yet. Skipping
app-e8e81040.js:109 Event: event
app-e8e81040.js:109  ::: Got a cleanup notification (remote feed 3642291480) :::
app-e8e81040.js:109 Event: event
app-e8e81040.js:133 Data channel not open yet. Skipping
app-e8e81040.js:133 Data channel not open yet. Skipping
```

**Comment by ancorgs** [comment]
@toabctl Maybe using chrom(e/ium) and not accessing through https?

https://github.com/jangouts/jangouts/blob/master/src/app/components/browser-info/browser-info.html#L37

**Comment by ancorgs** [comment]
@toabctl Still happening. Was related to https in the end?

**Comment by toabctl** [comment]
I'm using Version 49.0.2623.75 (64-bit) with https .

**Comment by toabctl** [comment]
For the record - there are client side javascript errors:
```
main plugin attached (janus.plugin.videoroom, id=3485495308)
app-e8e81040.js:109 Event: joined
app-e8e81040.js:109 Successfully joined room 2004
app-e8e81040.js:109 Consent dialog should be on now
app-e8e81040.js:109 Got a list of available publishers/feeds:
app-e8e81040.js:109 [Object]
app-e8e81040.js:109   >> [2649159357] ancor
vendor-f4c09c8a.js:33 TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at TypeError (native)
    at attachMediaStream (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:95:2275)
    at Object.fn (https://jangouts.suse.de/scripts/app-e8e81040.js:169:132)
    at h.$digest (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:34:3771)
    at h.$apply (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:34:5260)
    at https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:34:12594
    at i (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:32:21354)
    at https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:32:22808 undefined(anonymous function) @ vendor-f4c09c8a.js:33(anonymous function) @ vendor-f4c09c8a.js:33(anonymous function) @ vendor-f4c09c8a.js:100h.$digest @ vendor-f4c09c8a.js:34h.$apply @ vendor-f4c09c8a.js:34(anonymous function) @ vendor-f4c09c8a.js:34i @ vendor-f4c09c8a.js:32(anonymous function) @ vendor-f4c09c8a.js:32
vendor-f4c09c8a.js:33 TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at TypeError (native)
    at attachMediaStream (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:95:2275)
    at Object.fn (https://jangouts.suse.de/scripts/app-e8e81040.js:175:221)
    at h.$digest (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:34:3771)
    at h.$apply (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:34:5260)
    at https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:34:12594
    at i (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:32:21354)
    at https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:32:22808 undefined(anonymous function) @ vendor-f4c09c8a.js:33(anonymous function) @ vendor-f4c09c8a.js:33(anonymous function) @ vendor-f4c09c8a.js:100h.$digest @ vendor-f4c09c8a.js:34h.$apply @ vendor-f4c09c8a.js:34(anonymous function) @ vendor-f4c09c8a.js:34i @ vendor-f4c09c8a.js:32(anonymous function) @ vendor-f4c09c8a.js:32
app-e8e81040.js:109 Consent dialog should be off now
app-e8e81040.js:109  ::: Got a local stream :::
app-e8e81040.js:193 Got publisher SDP!
app-e8e81040.js:193 Object {type: "offer", sdp: "v=0
↵o=- 5101610022642324724 2 IN IP4 127.0.0.1
↵s…id:data
↵a=sctpmap:5000 webrtc-datachannel 1024
↵"}
%7B%7Bvm.feed.getPicture()%7D%7D:1 GET https://jangouts.suse.de/%7B%7Bvm.feed.getPicture()%7D%7D 404 (Not Found)
app-e8e81040.js:193 subscriber plugin attached (janus.plugin.videoroom, id=1057707164)
app-e8e81040.js:109 Event: event
app-e8e81040.js:109  ::: Got a message (listener) :::
app-e8e81040.js:109 {"videoroom":"attached","room":2004,"id":2649159357,"display":"ancor"}
app-e8e81040.js:109 Event: attached
app-e8e81040.js:199 Connection configured Object {audio: true, video: true}
app-e8e81040.js:109 Successfully attached to feed 2649159357 (ancor) in room 2004
vendor-f4c09c8a.js:33 TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at TypeError (native)
    at attachMediaStream (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:95:2275)
    at Object.fn (https://jangouts.suse.de/scripts/app-e8e81040.js:175:221)
    at h.$digest (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:34:3771)
    at h.$apply (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:34:5260)
    at https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:34:12594
    at i (https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:32:21354)
    at https://jangouts.suse.de/scripts/vendor-f4c09c8a.js:32:22808 undefined(anonymous function) @ vendor-f4c09c8a.js:33(anonymous function) @ vendor-f4c09c8a.js:33(anonymous function) @ vendor-f4c09c8a.js:100h.$digest @ vendor-f4c09c8a.js:34h.$apply @ vendor-f4c09c8a.js:34(anonymous function) @ vendor-f4c09c8a.js:34i @ vendor-f4c09c8a.js:32(anonymous function) @ vendor-f4c09c8a.js:32
app-e8e81040.js:193 Got SDP!
app-e8e81040.js:193 Object {type: "answer", sdp: "v=0
↵o=- 4262174576070684903 2 IN IP4 127.0.0.1
↵s…id:data
↵a=sctpmap:5000 webrtc-datachannel 1024
↵"}
app-e8e81040.js:109  ::: Got a message (listener) :::
app-e8e81040.js:109 {"videoroom":"event","room":2004,"configured":"ok"}
app-e8e81040.js:109 Event: event
app-e8e81040.js:109  ::: Got a message (listener) :::
app-e8e81040.js:109 {"videoroom":"event","room":2004,"started":"ok"}
app-e8e81040.js:109 Event: event
app-e8e81040.js:199 Connection configured Object {audio: true, video: true}
5app-e8e81040.js:133 Data channel not open yet. Skipping
```

**Comment by ancorgs** [comment]
Also for the record. Those errors are not preventing the connection. It worked with the same browser in a Jangouts instance hosted out of the VPN. So the root of evil is a network-related problem.
