### ISSUE TITLE
Node 18 `ERR_OSSL_EVP_UNSUPPORTED`

### ISSUE THREAD

**Issue by tacerus** [jangouts/jangouts#361]
Hi,

`npm start` with nodejs18 returns:

```
Starting the development server...
      
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/georg/jangouts/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/georg/jangouts/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/georg/jangouts/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/georg/jangouts/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/georg/jangouts/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/georg/jangouts/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/georg/jangouts/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/georg/jangouts/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/georg/jangouts/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^   
      
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/georg/jangouts/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/georg/jangouts/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/georg/jangouts/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/georg/jangouts/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/georg/jangouts/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/georg/jangouts/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/georg/jangouts/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/georg/jangouts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
ERROR: "start:react" exited with 1.
```

As a workaround, the environment variable `NODE_OPTIONS=--openssl-legacy-provider` can be applied.

https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

I think in the future some hashFunction will need to be adjusted?

Best,
Georg

**Comment by imobachgs** [comment]
Good catch! We are in the process of updating our dependencies, so perhaps it will fix this issue too.

**Comment by ancorgs** [comment]
Does this affect the new React-based version? I think it doesn't so I'm closing this. Feel free to reopen if you experience this in the current version at the master branch.
